spring:
  h2:
    console:
      enabled: true
  application:
    name: tasks_app
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:task_db;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false